import sharp from 'sharp';
import ffmpeg from 'ffmpeg-static';
import { execFileSync } from 'node:child_process';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { parse, join } from 'node:path';
import { descriptions } from './media-metadata.mjs';

const source = fileURLToPath(new URL('../src/Components/Gallery/imgs/', import.meta.url));
const destination = fileURLToPath(new URL('../src/Components/Gallery/optimized/', import.meta.url));
await mkdir(destination, { recursive: true });
const { excludedFiles } = JSON.parse(await readFile(new URL('../src/Components/Gallery/media-settings.json', import.meta.url), 'utf8'));
const files = (await readdir(source)).filter(name => /\.(jpe?g|png|webp|mov|mp4)$/i.test(name) && !excludedFiles.includes(name))
  .sort((a, b) => a.localeCompare(b, 'en', { numeric: true }));
const imports = [];
const records = [];
const ids = new Set();

for (const [index, file] of files.entries()) {
  const video = /\.(mov|mp4)$/i.test(file);
  const stem = parse(file).name;
  const location = stem.replace(/\s*(?:\(\d+\)|\d+)$/, '').replace(/^siena$/, 'Siena').trim();
  const sequence = Number(stem.match(/(?:\((\d+)\)|(\d+))$/)?.slice(1).find(Boolean) || 1);
  const slug = stem.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/-$/g, '');
  const id = `${video ? 'film' : 'photo'}-${slug}`;
  if (ids.has(id)) throw new Error(`Duplicate media identifier: ${id}`);
  ids.add(id);
  const input = join(source, file);
  const output = join(destination, id);
  let width, height;
  if (video) {
    // H.264/AAC MP4 with its index at the front for progressive browser playback.
    execFileSync(ffmpeg, ['-hide_banner', '-loglevel', 'error', '-y', '-i', input,
      '-map', '0:v:0', '-map', '0:a:0?', '-c:v', 'libx264', '-preset', 'medium', '-crf', '23',
      '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-b:a', '96k', '-movflags', '+faststart', '-map_metadata', '-1', `${output}.mp4`]);
    const frame = execFileSync(ffmpeg, ['-hide_banner', '-loglevel', 'error', '-ss', '0', '-i', `${output}.mp4`,
      '-frames:v', '1', '-f', 'image2pipe', '-vcodec', 'png', 'pipe:1'], { maxBuffer: 20 * 1024 * 1024 });
    ({ width, height } = await sharp(frame).resize({ width: 1200, height: 1200, fit: 'inside', withoutEnlargement: true }).webp({ quality: 82 }).toFile(`${output}-poster.webp`));
    imports.push(`import source${index} from './optimized/${id}.mp4';`, `import preview${index} from './optimized/${id}-poster.webp';`);
  } else {
    ({ width, height } = await sharp(input).rotate().resize({ width: 1800, height: 1800, fit: 'inside', withoutEnlargement: true }).webp({ quality: 84 }).toFile(`${output}.webp`));
    await sharp(input).rotate().resize({ width: 640, withoutEnlargement: true }).webp({ quality: 79 }).toFile(`${output}-thumb.webp`);
    imports.push(`import source${index} from './optimized/${id}.webp';`, `import preview${index} from './optimized/${id}-thumb.webp';`);
  }
  const metadata = { id, kind: video ? 'video' : 'photo', filename: file, location, sequence, width, height,
    alt: descriptions[file] || `${video ? 'A moving postcard' : 'Photograph'} from ${location}` };
  records.push(`  { ...${JSON.stringify(metadata)}, src: source${index}, preview: preview${index} }`);
}
const module = `// Generated by npm run media:prepare. Edit filenames or scripts/media-metadata.mjs instead.\n${imports.join('\n')}\n\nexport type MediaItem = {\n  id: string; kind: 'photo' | 'video'; filename: string; location: string; sequence: number;\n  width: number; height: number; alt: string; src: string; preview: string;\n};\n\nexport const media: MediaItem[] = [\n${records.join(',\n')}\n];\n`;
await writeFile(new URL('../src/Components/Gallery/media.ts', import.meta.url), module);
console.log(`Prepared ${records.length} media items; originals unchanged.`);
